@startuml
skinparam dpi 300

class RepoCollection

class RepoFile

class Repo

class Metadata

abstract class Database

class PrimaryDb
class GroupDb
class FilelistDb
class OtherDb
class UpdateDb

class Package

class Format

class DependencyEntry

class RPM

class Provides<list>

class Depends<list>

class Conflicts<list>

class Obsoletes<list>

RepoCollection "1" o-- "1..*" RepoFile
RepoCollection "1" *-- "1..*" Repo
RepoFile "1" o-- "1..*" Repo
Repo "1" *-- "1" Metadata

Metadata "1" *-- "1" PrimaryDb
Metadata "1" *-- "0..1" GroupDb
Metadata "1" *-- "0..1" FilelistDb
Metadata "1" *-- "0..1" OtherDb
Metadata "1" *-- "0..1" UpdateDb

PrimaryDb <|-- Database
GroupDb <|-- Database
FilelistDb <|-- Database
OtherDb <|-- Database
UpdateDb <|-- Database

Database "1" o-- "1..*" Package

Package "1" o-- "1" RPM
Package "1" *-- "1" Format
Package "1..*" *-- "1..*" Package

Format "1" *-- "1" Provides
Format "1" *-- "1" Depends
Format "1" *-- "1" Conflicts
Format "1" *-- "1" Obsoletes

Provides "1" *-- "1..*" DependencyEntry
Depends "1" *-- "1..*" DependencyEntry
Conflicts "1" *-- "1..*" DependencyEntry
Obsoletes "1" *-- "1..*" DependencyEntry


@enduml